### PR TITLE
S28 3214 Switch watch page

### PR DESCRIPTION
**Pull request by LaurenceRawlings**
### Change description

- removed banner on watch mk page
- switched watch mk page to `/watch` and removed the old watch page

> [!IMPORTANT]
> This PR requires manual testing by QA. Please notify the QA team @hmcts/pre-rec-evidence-qa.

**QA instructions**

- mk content should now be viewable at `/watch` using mkplayer
- `/watch-mk` page should no longer be accessible

### CODE REVIEW

**Comment by cristianemarsilio** [comment]
@LaurenceRawlings - if this PR gets merged, will the change be reflected in the portal in Prod? Is there a way to apply this change only to the Demo portal? thanks

**Comment by LaurenceRawlings** [comment]
I have changed the base branch to `demo`, merging here will deploy to demo

**Review by lucas-phillips28 — APPROVED** [review]
Looks good to me. We probably should change the file names from `watch-mk` to `watch` but that can be done in the future

**Review by cristianemarsilio — APPROVED** [review]
Manually tested the changes in preview.

**Pull request merged**
